version: '2.2'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 9301
      - 9302
      - 9303
    networks:
      nginx:
        aliases:
          - nginx
          - es1
          - es2
          - es3

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1:9301,es2:9302,es3:9303"
      - "network.publish_host=es1"
      - "transport.tcp.port=9301"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
    networks:
      - es1
      - nginx

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1:9301,es2:9302,es3:9303"
      - "network.publish_host=es2"
      - "transport.tcp.port=9302"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200
    networks:
      - es2
      - nginx

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1:9301,es2:9302,es3:9303"
      - "network.publish_host=es3"
      - "transport.tcp.port=9303"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9203:9200
    networks:
      - es3
      - nginx

networks:
  es1:
  es2:
  es3:
  nginx:
